# TODO: Distinguish between dev & production dockerfile?

services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USERNAME: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

volumes:
  postgres_data:
